"""
AMP & PM ADVENTURE — 出版生態系統
====================================
9 產品類型 × 10 階段流水線 × 人工審核閘門
每本書從選題到上架到行銷，全部追蹤。
"""

# ═══ 市場規範：各產品類型業界標準 ═══

MARKET_STANDARDS = {
    "ebook": {
        "name": "電子工具書",
        "icon": "📚",
        "word_target": "15,000 - 30,000 字",
        "chapters": "6 - 10 章",
        "format": "EPUB reflowable (流式排版)",
        "target_readers": "初學者到中階",
        "price_range": "NT$150 - 350",
        "platforms": "KDP / Readmoo / Google Play Books / Pubu",
        "content_style": "步驟式教學 + 圖解 + 實例 + 總結",
        "key_diff": "每章要有實際操作步驟，不是純理論",
    },
    "kidbook": {
        "name": "兒童繪本",
        "icon": "🧒",
        "word_target": "500 - 1,500 字",
        "pages": "24 - 32 頁",
        "format": "EPUB fixed-layout (固定版式)",
        "target_readers": "3 - 6 歲親子共讀",
        "price_range": "NT$120 - 250",
        "platforms": "KDP / Readmoo",
        "content_style": "圖為主字為輔，每頁 1-2 句，有教育意義",
        "key_diff": "插畫佔 70% 以上，文字簡潔有韻律",
    },
    "comic": {
        "name": "漫畫/圖像小說",
        "icon": "🎨",
        "word_target": "視頁數而定，對話框為主",
        "pages": "30 - 200 頁",
        "format": "EPUB fixed-layout / PDF",
        "target_readers": "全年齡或指定族群",
        "price_range": "NT$80 - 300",
        "platforms": "KDP / Readmoo / LINE WEBTOON",
        "content_style": "分鏡→草稿→線稿→上色→嵌字",
        "key_diff": "畫面敘事能力 > 文字敘事",
    },
    "novel": {
        "name": "長篇小說",
        "icon": "📖",
        "word_target": "50,000 - 150,000 字",
        "chapters": "30 - 50 章以上",
        "format": "EPUB reflowable",
        "target_readers": "成年讀者",
        "price_range": "NT$200 - 450",
        "platforms": "KDP / Readmoo / Google Play Books",
        "content_style": "三幕劇結構 / 起承轉合",
        "key_diff": "人物弧線完整，情節有起伏",
    },
    "short_story": {
        "name": "短篇小說",
        "icon": "✏️",
        "word_target": "3,000 - 10,000 字",
        "chapters": "1 - 5 章",
        "format": "EPUB reflowable",
        "target_readers": "通勤閱讀族群",
        "price_range": "NT$50 - 120",
        "platforms": "KDP / Readmoo",
        "content_style": "單一主題，有反轉或情感衝擊",
        "key_diff": "節奏快，15 分鐘內可讀完",
    },
    "magazine": {
        "name": "雜誌/專題刊物",
        "icon": "📰",
        "word_target": "10,000 - 30,000 字 (整期)",
        "articles": "5 - 10 篇文章",
        "format": "PDF / EPUB fixed-layout",
        "target_readers": "特定興趣族群",
        "price_range": "NT$100 - 250",
        "platforms": "KDP / Readmoo / 自有網站",
        "content_style": "封面故事 + 專欄 + 資訊圖表",
        "key_diff": "時效性強，視覺設計為先",
    },
    "edu_book": {
        "name": "學習用書/教材",
        "icon": "🎓",
        "word_target": "20,000 - 50,000 字",
        "chapters": "10 - 20 單元",
        "format": "EPUB reflowable / PDF",
        "target_readers": "學生/進修者",
        "price_range": "NT$200 - 500",
        "platforms": "KDP / Readmoo",
        "content_style": "單元式 + 練習題 + 解答",
        "key_diff": "要有評量機制，不是只讀不練",
    },
    "exam_book": {
        "name": "考試用書",
        "icon": "📝",
        "word_target": "30,000 - 80,000 字",
        "chapters": "依照考試科目分章",
        "format": "EPUB reflowable / PDF",
        "target_readers": "考生",
        "price_range": "NT$300 - 800",
        "platforms": "KDP / Readmoo",
        "content_style": "題型分析 + 模擬試題 + 詳解",
        "key_diff": "命中率是關鍵，要有考情分析",
    },
    "reference_book": {
        "name": "技術手冊/工具書",
        "icon": "🔧",
        "word_target": "15,000 - 40,000 字",
        "chapters": "5 - 15 章",
        "format": "EPUB reflowable / PDF",
        "target_readers": "開發者/專業人士",
        "price_range": "NT$250 - 600",
        "platforms": "KDP / Readmoo",
        "content_style": "指令速查 + 實戰範例 + 最佳實踐",
        "key_diff": "查找方便，不是線性閱讀",
    },
}
